#!/usr/bin/env python3
import pymei as pm
import sys
import numpy as np

path = sys.argv[1]
data = pm.load(path)

a = float("inf")
b = float("-inf")

for tr in data:
    _a = tr.data.min()
    _b = tr.data.max()
    if _a < a: a = _a
    if _b > b: b = _b

print("min: {} max: {}".format(a, b))
